#MERUBAH LIST MENJADI SET
#MASUKKAN DATA LIST DAN UBAH MENGGUNAKAN FUNGSI SET
data_list = ['Satu','Dua','Tiga']
s = set(data_list)
#VARIABEL S UNTUK MENAMPILKAN DATA LIST DIUBAH MENJADI SET
print(s)

#MERUBAH SET MENJADI LIST
#MASUKKAN DATA SET DAN UBAH MENGGUNAKAN FUNGSI LIST
data_set = {'Satu','Dua','Tiga'}
l = list(data_set)
#VARIABEL l UNTUK MENAMPILKAN DATA SET DIUBAH MENJADI LIST
print(l)

#MERUBAH DATA TUPLE MENJADI SET
#MASUKKAN DATA TUPLE DAN UBAH MENGGUNAKAN FUNGSI SET
data_tuple = ('Satu','Dua','Tiga')
ubah_set = set(data_tuple)
#VARIABEL ubah_set UNTUK MENAMPILKAN DATA TUPLE TELAH DIUBAH MENJADI SET
print(ubah_set)

#MERUBAH DATA SET MENJADI TUPLE
#MASUKKAN DATA SET DAN UBAH MENGGUNAKAN FUNGSI TUPLE
data_Set = {'Satu','Dua','Tiga'}
ubah_tuple = tuple(data_Set)
#VARIABEL ubah_tuple UNTUK MENAMPILKAN DATA SET MENJADI TUPLE
print(ubah_tuple)


